services:
  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - altairis-network

  redis:
    image: redis:latest
    platform: linux/amd64
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - altairis-network

  admin-api:
    build:
      context: ./docker/admin-api
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5001:8080"
    depends_on:
      - database
      - redis
    networks:
      - altairis-network

  client-api:
    build:
      context: ./docker/client-api
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5002:8080"
    depends_on:
      - database
      - redis
    networks:
      - altairis-network

  providers-api:
    build:
      context: ./docker/providers-api
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5003:8080"
    depends_on:
      - database
      - redis
    networks:
      - altairis-network

  external-client-api:
    build:
      context: ./docker/external-client-api
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5005:8080"
    depends_on:
      - database
      - redis
      - reservations-api
    networks:
      - altairis-network

  reservations-api:
    build:
      context: ./docker/reservations-api
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5004:8080"
    depends_on:
      - database
      - redis
    networks:
      - altairis-network

  scheduled-api:
    build:
      context: ./docker/scheduled-api
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5006:8080"
    depends_on:
      - database
      - redis
    networks:
      - altairis-network

  admin-web:
    build:
      context: ./docker/admin-web
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - admin-api
    networks:
      - altairis-network

  client-web:
    build:
      context: ./docker/client-web
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3002:3000"
    depends_on:
      - client-api
    networks:
      - altairis-network

volumes:
  mariadb-data:
  redis-data:

networks:
  altairis-network:
    driver: bridge
