global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'dotnet-apis'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'admin-api:8080'
          - 'client-api:8080'
          - 'providers-api:8080'
          - 'reservations-api:8080'
          - 'external-client-api:8080'
          - 'scheduled-api:8080'

  - job_name: 'nextjs-webs'
    scrape_interval: 15s
    metrics_path: '/api/metrics'
    static_configs:
      - targets:
          - 'admin-web:3000'
          - 'client-web:3000'
